export const directorFeatures = [
  { label: "director.dashboard", icon: "📊", route: "/rbac/director", description: "University Performance Overview, KPI Summary, Alerts & Notices" },
  { label: "director.analyticsReports", icon: "📈", route: "/rbac/director/analytics", description: "Department-wise Reports, Statistics, Finance, Trends, HR Insights" },
  { label: "director.departments", icon: "🏢", route: "/rbac/director/departments", description: "Academic Affairs, HR, Finance, Admissions, IT, R&D" },
  { label: "director.approvalCenter", icon: "✅", route: "/rbac/director/approvals", description: "Budget, Policy, Recruitment, Procurement Approvals" },
  { label: "Procurement", icon: "📦", route: "/rbac/director/procurement", description: "Purchase Orders, Vendor Management, Procurement Analytics" },
  { label: "director.strategicPlanning", icon: "🗺️", route: "/rbac/director/strategic-planning", description: "Annual Plans, Accreditation, Risk Management" },
  { label: "director.communication", icon: "📢", route: "/rbac/director/communication", description: "Notices, Circulars, External Comms" },
  { label: "director.auditCompliance", icon: "🕵️", route: "/rbac/director/audit", description: "Audit Reports, Accreditation, Legal Docs" },
  { label: "director.meetingsCalendar", icon: "🗓️", route: "/rbac/director/calendar", description: "Scheduler, Minutes, Events" },
  { label: "director.userManagement", icon: "👥", route: "/rbac/director/users", description: "Roles, Permissions, Admin Controls" },
  { label: "director.settings", icon: "⚙️", route: "/rbac/director/settings", description: "Profile, Branding, Notifications" },
  { label: "director.workspace", icon: "🗂️", route: "/rbac/director/workspace", description: "Director's Workspace, Quick Access, Tools" },
  { label: "director.helpSupport", icon: "🆘", route: "/rbac/director/support", description: "Technical Support, Handbook" },
]; 