export const marketingHeadFeatures = [
  { label: "marketingHead.dashboard", icon: "📊", route: "/rbac/marketing-head", description: "Marketing Performance Overview, Campaign KPIs, Alerts & Notices" },
  { label: "marketingHead.reportingAnalytics", icon: "📈", route: "/rbac/marketing-head/analytics", description: "Campaign Analytics, ROI Reports, Lead Generation Stats" },
  { label: "marketingHead.campaign", icon: "🎯", route: "/rbac/marketing-head/campaigns", description: "Campaign Planning, Execution, and Tracking" },
  { label: "marketingHead.leads", icon: "👥", route: "/rbac/marketing-head/leads", description: "Lead Tracking, Qualification, and Conversion" },
  { label: "proposalManager.contentHub", icon: "📝", route: "/rbac/marketing-head/content", description: "Content Creation, Management, and Distribution" },
  { label: "marketingHead.socialMedia", icon: "📱", route: "/rbac/marketing-head/social", description: "Social Media Management and Analytics" },
  { label: "marketingHead.events", icon: "🎪", route: "/rbac/marketing-head/events", description: "Event Planning and Management" },
  { label: "marketingHead.budget", icon: "💰", route: "/rbac/marketing-head/budget", description: "Marketing Budget and Expense Management" },
  { label: "admissionHead.procurement", icon: "📦", route: "/rbac/marketing-head/procurement", description: "Purchase Requests, Vendor Management, Procurement Tracking" },
  { label: "admissionHead.team", icon: "👥", route: "/rbac/marketing-head/team", description: "Team Management and Collaboration" },
  { label: "director.settings", icon: "⚙️", route: "/rbac/marketing-head/settings", description: "Profile, Preferences, Notifications" },
  { label: "marketingHead.workspace", icon: "🗂️", route: "/rbac/marketing-head/workspace", description: "Marketing Workspace, Quick Access, Tools" },
  { label: "marketingHead.helpSupport", icon: "🆘", route: "/rbac/marketing-head/support", description: "Technical Support, Handbook" },
]; 