export const marketingHeadFeatures = [
  { label: "Dashboard", icon: "📊", route: "/rbac/marketing-head", description: "Marketing Performance Overview, Campaign KPIs, Alerts & Notices" },
  { label: "Analytics & Reports", icon: "📈", route: "/rbac/marketing-head/analytics", description: "Campaign Analytics, ROI Reports, Lead Generation Stats" },
  { label: "Campaign Management", icon: "🎯", route: "/rbac/marketing-head/campaigns", description: "Campaign Planning, Execution, and Tracking" },
  { label: "Lead Management", icon: "👥", route: "/rbac/marketing-head/leads", description: "Lead Tracking, Qualification, and Conversion" },
  { label: "Content Hub", icon: "📝", route: "/rbac/marketing-head/content", description: "Content Creation, Management, and Distribution" },
  { label: "Social Media", icon: "📱", route: "/rbac/marketing-head/social", description: "Social Media Management and Analytics" },
  { label: "Events", icon: "🎪", route: "/rbac/marketing-head/events", description: "Event Planning and Management" },
  { label: "Budget", icon: "💰", route: "/rbac/marketing-head/budget", description: "Marketing Budget and Expense Management" },
  { label: "Procurement", icon: "🛒", route: "/rbac/marketing-head/procurement", description: "Purchase Requests, Vendor Management, Procurement Tracking" },
  { label: "Team", icon: "👥", route: "/rbac/marketing-head/team", description: "Team Management and Collaboration" },
  { label: "Settings", icon: "⚙️", route: "/rbac/marketing-head/settings", description: "Profile, Preferences, Notifications" },
  { label: "Workspace", icon: "🗂️", route: "/rbac/marketing-head/workspace", description: "Marketing Workspace, Quick Access, Tools" },
  { label: "Help & Support", icon: "🆘", route: "/rbac/marketing-head/support", description: "Technical Support, Handbook" },
]; 