export const proposalManagerFeatures = [
  { label: "director.dashboard", icon: "📊", route: "/rbac/proposal-manager", description: "Performance Overview, KPI Summary, Alerts & Notices" },
  { label: "proposalManager.companyIntelligence", icon: "🌐", route: "/rbac/proposal-manager/company-intelligence", description: "RFP issuer financials, trends, and customers from public sources" },
  { label: "proposalManager.sourceDocs", icon: "📄", route: "/rbac/proposal-manager/source-docs", description: "Source documents and reference materials" },
  { label: "proposalManager.manageTeam", icon: "👥", route: "/rbac/proposal-manager/team", description: "Team Management and Collaboration" },
  { label: "proposalManager.bidVault", icon: "📦", route: "/rbac/proposal-manager/bid-vault", description: "Bid repository and submissions" },
  { label: "proposalManager.captureStrategy", icon: "🗺️", route: "/rbac/proposal-manager/capture-strategy", description: "Capture strategy and planning" },
  { label: "proposalManager.contentHub", icon: "📝", route: "/rbac/proposal-manager/content-hub", description: "Content library and assets" },
  { label: "proposalManager.pricing", icon: "💰", route: "/rbac/proposal-manager/pricing", description: "Pricing and cost proposals" },
  { label: "proposalManager.communication", icon: "💬", route: "/rbac/proposal-manager/communication", description: "Internal Communication Hub" },
  { label: "proposalManager.compliance", icon: "🕵️", route: "/rbac/proposal-manager/compliance", description: "Audit, Compliance, Legal Docs" },
  { label: "proposalManager.meetingsCalendar", icon: "🗓️", route: "/rbac/proposal-manager/meetings-calendar", description: "Scheduler, Minutes, Events" },
  { label: "director.userManagement", icon: "👤", route: "/rbac/proposal-manager/user-management", description: "Roles, Permissions, Admin Controls" },
  { label: "director.workspace", icon: "📁", route: "/rbac/proposal-manager/workspace", description: "Workspace and tasks" },
  { label: "director.helpSupport", icon: "🆘", route: "/rbac/proposal-manager/help-support", description: "Technical Support, Handbook" },
  { label: "director.settings", icon: "⚙️", route: "/rbac/proposal-manager/settings", description: "Profile, Branding, Notifications" },
];
