export const proposalManagerFeatures = [
  { label: "director.dashboard", icon: "📊", route: "/app/dashboard", description: "Performance Overview, KPI Summary, Alerts & Notices" },
  { label: "proposalManager.grants", icon: "🏛️", route: "/app/grants", description: "Federal Grants.gov (live) + private foundations (live IRS/ProPublica) + state/local-eligible Grants.gov + SAM.gov contracts (curated)" },
  { label: "director.workspace", icon: "📁", route: "/app/workspace", description: "Workspace and tasks" },
  { label: "proposalManager.companyIntelligence", icon: "🌐", route: "/app/company-intelligence", description: "RFP issuer financials, trends, and customers from public sources" },
  { label: "proposalManager.competitiveIntelligence", icon: "🎯", route: "/app/competitive-intelligence", description: "Look up any competitor or compare curated peers — datasheets and differentiators" },
  { label: "proposalManager.sourceDocs", icon: "📄", route: "/app/source-docs", description: "Source documents and reference materials" },
  { label: "proposalManager.manageTeam", icon: "👥", route: "/app/team", description: "Team Management and Collaboration" },
  { label: "proposalManager.rfpCollaboration", icon: "🤝", route: "/app/rfp-collaboration", description: "Assign RFP questions to auditors, AI drafts, review, activity log" },
  { label: "proposalManager.technicalSolutioning", icon: "🏗️", route: "/app/technical-solutioning", description: "AI solution architecture from reference designs and RFP requirements" },
  { label: "proposalManager.topology", icon: "🧭", route: "/app/topology", description: "Customer infrastructure topography with JUNO overlay and RFP legends" },
  { label: "proposalManager.bidVault", icon: "📦", route: "/app/bid-vault", description: "Bid repository and submissions" },
  { label: "proposalManager.scoring", icon: "🏅", route: "/app/scoring", description: "Win/loss scoring, debrief ingest, and product capability gaps" },
  { label: "proposalManager.winSlide", icon: "🖼️", route: "/app/win-slide", description: "Post-selection win slide: POV, proof, and who we won or lost against" },
  { label: "proposalManager.captureStrategy", icon: "🗺️", route: "/app/capture-strategy", description: "Capture strategy and planning" },
  { label: "proposalManager.contentHub", icon: "📝", route: "/app/content-hub", description: "Content library and assets" },
  { label: "proposalManager.pricing", icon: "💰", route: "/app/pricing", description: "Pricing and cost proposals" },
  { label: "proposalManager.communication", icon: "💬", route: "/app/communication", description: "Internal Communication Hub" },
  { label: "proposalManager.compliance", icon: "🕵️", route: "/app/compliance", description: "Audit, Compliance, Legal Docs" },
  { label: "proposalManager.meetingsCalendar", icon: "🗓️", route: "/app/meetings-calendar", description: "Scheduler, Minutes, Events" },
  { label: "director.userManagement", icon: "👤", route: "/app/user-management", description: "Roles, Permissions, Admin Controls" },
  { label: "director.helpSupport", icon: "🆘", route: "/app/help-support", description: "Technical Support, Handbook" },
  { label: "director.settings", icon: "⚙️", route: "/app/settings", description: "Profile, Branding, Notifications" },
];
