import { getDocuments } from "./proposalManagerStorage.js";
import { calendarApi } from "../../../services/calendarApi.js";
import {
  generateMockCalendarEvents,
  getMockTeamSummary,
} from "./proposalManagerCalendarMockData.js";
import { getTrialSession } from "../../../services/trialAuthSession.js";
import { parseLocalStorageJson } from "../../../utils/safeStorage.js";
import { hydrateShortlistFromServer, listShortlist, shortlistEventId } from "./shortlistStore.js";
import { assignmentEventId, hydrateTeamFromServer, listAssignments } from "./teamStore.js";
import { listSourceDocDeadlines } from "./sourceDocsDeadlineService.js";
import { parseDateToISO } from "./calendarDateParse.js";

export { parseDateToISO } from "./calendarDateParse.js";

/** Demo schedule merged with live API data for a full, polished calendar view. */
const USE_MOCK_CALENDAR = true;

function isTrialUserSession() {
  const session = getTrialSession();
  const user = parseLocalStorageJson("rbac_current_user");
  return Boolean(session?.token || user?.isTrialUser);
}

const EMPTY_TEAM = {
  auditors: [],
  totals: { assigned: 0, submitted: 0, approved: 0, unassigned: 0, inProgress: 0 },
};

const SHORTLIST_DEADLINE_COLOR = "#dc2626";
const ASSIGNMENT_DEADLINE_COLOR = "#2563eb";
const SOURCE_DOC_DEADLINE_COLOR = "#b91c1c";

/** Map shortlisted grants/RFPs to all-day calendar deadline events. */
export function shortlistItemsToCalendarEvents() {
  return listShortlist()
    .map((item) => {
      const iso = parseDateToISO(item.deadline);
      if (!iso) return null;
      const sourceLabel =
        item.source === "sam" ? "SAM" : item.source === "alt" ? "Grant" : "Grant";
      return {
        id: shortlistEventId(item.id),
        title: `${sourceLabel} deadline: ${item.title}`,
        start: iso,
        allDay: true,
        type: "deadline",
        color: SHORTLIST_DEADLINE_COLOR,
        bidName: item.number || item.title,
        description: [item.agency, item.number].filter(Boolean).join(" · "),
        source: "shortlist",
        shortlistId: item.id,
        autoGenerated: true,
      };
    })
    .filter(Boolean);
}

/** Map team assignments to all-day calendar deadline events. */
export function assignmentItemsToCalendarEvents() {
  return listAssignments()
    .map((item) => {
      const iso = parseDateToISO(item.deadline);
      if (!iso) return null;
      return {
        id: assignmentEventId(item.id),
        title: `Assignment: ${item.task}`,
        start: iso,
        allDay: true,
        type: "deadline",
        color: ASSIGNMENT_DEADLINE_COLOR,
        bidName: item.assigned || item.task,
        description: [item.assigned, item.status, item.progress].filter(Boolean).join(" · "),
        source: "assignment",
        assignmentId: item.id,
        autoGenerated: true,
      };
    })
    .filter(Boolean);
}

/** Application deadlines from AI-scanned Source Docs. */
export function sourceDocItemsToCalendarEvents() {
  return listSourceDocDeadlines().map((item) => ({
    id: item.id,
    title: `${item.event}: ${item.docName}`,
    start: item.date,
    allDay: true,
    type: "deadline",
    color: SOURCE_DOC_DEADLINE_COLOR,
    bidName: item.docName,
    description: item.rawText || item.event,
    source: "source-doc",
    documentId: item.docId,
    autoGenerated: true,
  }));
}

const DEADLINE_FACT_KEYS = new Set([
  "proposal_due_date",
  "questions_due_date",
]);

const DEADLINE_KEY_RE = /due|deadline|submission|questions?_due/i;

const DEADLINE_LABELS = {
  proposal_due_date: "Proposal submission deadline",
  questions_due_date: "Questions due",
};

/** Build deadline payloads for /calendar/sync-deadlines from workspace source docs. */
export function buildDeadlineSyncPayload() {
  const docs = getDocuments();
  const events = [];

  for (const doc of docs) {
    const bidName = doc.name || "RFP document";
    for (const fact of doc.extractedFacts || []) {
      if (!fact?.key || !fact?.value) continue;
      const isDeadline =
        DEADLINE_FACT_KEYS.has(fact.key) || DEADLINE_KEY_RE.test(String(fact.key));
      if (!isDeadline) continue;
      const iso = parseDateToISO(fact.value);
      if (!iso) continue;
      const label = DEADLINE_LABELS[fact.key] || String(fact.key).replace(/_/g, " ");
      events.push({
        stableKey: `${doc.id}_${fact.key}_${iso}`,
        title: `${label}: ${bidName}`,
        start: iso,
        allDay: true,
        documentId: doc.id,
        bidName,
        description: fact.value,
        type: "deadline",
      });
    }
  }

  return events;
}

export async function syncRfpDeadlinesFromStorage() {
  const events = buildDeadlineSyncPayload();
  if (events.length === 0) return { synced: 0 };
  const { data } = await calendarApi.syncDeadlines(events);
  return data;
}

function mergeEvents(live, mock) {
  const byId = new Map();
  for (const ev of mock) byId.set(ev.id, ev);
  for (const ev of live) byId.set(ev.id, ev);
  return [...byId.values()].sort((a, b) => String(a.start).localeCompare(String(b.start)));
}

function mergeTeamSummary(live, mock) {
  if (!live?.auditors?.length) return mock;
  const mockAuditors = mock.auditors || [];
  const mergedAuditors = live.auditors.map((a, i) => ({
    ...mockAuditors[i % mockAuditors.length],
    ...a,
    name: a.name || mockAuditors[i % mockAuditors.length]?.name,
  }));
  return {
    ...mock,
    ...live,
    auditors: mergedAuditors.length ? mergedAuditors : mock.auditors,
    totals: {
      ...mock.totals,
      ...live.totals,
    },
  };
}

export async function loadCalendarBundle({ hydrate = true } = {}) {
  const trial = isTrialUserSession();
  const useMock = USE_MOCK_CALENDAR && !trial;

  if (trial && hydrate) {
    // Silent hydrate — notifying would re-trigger calendar refresh subscribers.
    await Promise.all([
      hydrateShortlistFromServer({ notify: false }).catch(() => {}),
      hydrateTeamFromServer({ notify: false }).catch(() => {}),
    ]);
  }

  const shortlistEvents = trial ? shortlistItemsToCalendarEvents() : [];
  const assignmentEvents = trial ? assignmentItemsToCalendarEvents() : [];
  const sourceDocEvents = trial ? sourceDocItemsToCalendarEvents() : [];
  const overlayEvents = [...shortlistEvents, ...assignmentEvents, ...sourceDocEvents];

  await syncRfpDeadlinesFromStorage().catch(() => {});
  const mockEvents = useMock ? generateMockCalendarEvents() : [];
  const mockTeam = useMock ? getMockTeamSummary() : EMPTY_TEAM;

  try {
    const [eventsRes, teamRes] = await Promise.all([
      calendarApi.listEvents(),
      calendarApi.teamSummary(),
    ]);
    const liveEvents = eventsRes.data?.events || [];
    const liveTeam = teamRes.data || null;
    const baseEvents = useMock ? mergeEvents(liveEvents, mockEvents) : liveEvents;
    return {
      events: mergeEvents(baseEvents, overlayEvents),
      // Trial: no seeded auditor roster — blank team panel
      team: useMock ? mergeTeamSummary(liveTeam, mockTeam) : EMPTY_TEAM,
      hasDemo: useMock,
    };
  } catch {
    return {
      events: mergeEvents(mockEvents, overlayEvents),
      team: mockTeam,
      hasDemo: useMock,
    };
  }
}

export function toFullCalendarEvent(ev) {
  const start = ev.allDay ? String(ev.start).slice(0, 10) : ev.start;
  const end = ev.end ? (ev.allDay ? String(ev.end).slice(0, 10) : ev.end) : undefined;
  return {
    id: ev.id,
    title: ev.title,
    start,
    end,
    allDay: Boolean(ev.allDay),
    backgroundColor: ev.color,
    borderColor: ev.color,
    extendedProps: { ...ev },
  };
}
